package com.b3a5t001.biome_nexus.items;

import com.b3a5t001.biome_nexus.blocks.ModBlocks;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.ItemGroups;

public class ModItemGroup {
    public static void init(){
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.INGREDIENTS).register(
                entries -> {
                    entries.add(ModItems.SULFUR_DUST);
                    entries.add(ModItems.COPPER_NUGGET);
                    entries.add(ModItems.JADE_BRICK);
                    entries.add(ModItems.JADE_CRYSTAL);
                    entries.add(ModItems.RAW_TIN);
                    entries.add(ModItems.TIN_INGOT);
                    entries.add(ModItems.TIN_NUGGET);
                    entries.add(ModItems.STEEL_INGOT);
                    entries.add(ModItems.STEEL_NUGGET);
                    entries.add(ModItems.AURORITE_CRYSTAL);
                    entries.add(ModItems.AURORITE_ALLOY);
                    entries.add(ModItems.GRACE_SMITHING_TEMPLATE);
                }
        );
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COMBAT).register(
                entries -> {
                    entries.add(ModItems.COPPER_SWORD);
                    entries.add(ModItems.AURORITE_SWORD);
                    entries.add(ModItems.STEEL_SWORD);
                    entries.add(ModItems.COPPER_AXE);
                    entries.add(ModItems.AURORITE_AXE);
                    entries.add(ModItems.STEEL_AXE);
                    entries.add(ModItems.COPPER_HELMET);
                    entries.add(ModItems.AURORITE_HELMET);
                    entries.add(ModItems.STEEL_HELMET);
                    entries.add(ModItems.COPPER_CHESTPLATE);
                    entries.add(ModItems.AURORITE_CHESTPLATE);
                    entries.add(ModItems.STEEL_CHESTPLATE);
                    entries.add(ModItems.COPPER_LEGGINGS);
                    entries.add(ModItems.AURORITE_LEGGINGS);
                    entries.add(ModItems.STEEL_LEGGINGS);
                    entries.add(ModItems.COPPER_BOOTS);
                    entries.add(ModItems.AURORITE_BOOTS);
                    entries.add(ModItems.STEEL_BOOTS);
                }
        );
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.TOOLS).register(
                entries -> {
                    entries.add(ModItems.COPPER_SHOVEL);
                    entries.add(ModItems.AURORITE_SHOVEL);
                    entries.add(ModItems.STEEL_SHOVEL);
                    entries.add(ModItems.COPPER_PICKAXE);
                    entries.add(ModItems.AURORITE_PICKAXE);
                    entries.add(ModItems.STEEL_PICKAXE);
                    entries.add(ModItems.COPPER_AXE);
                    entries.add(ModItems.AURORITE_AXE);
                    entries.add(ModItems.STEEL_AXE);
                    entries.add(ModItems.COPPER_HOE);
                    entries.add(ModItems.AURORITE_HOE);
                    entries.add(ModItems.STEEL_HOE);
                }
        );
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(
                entries -> {
                    entries.add(ModBlocks.COPPER_CHAIN);
                    entries.add(ModBlocks.EXPOSED_COPPER_CHAIN);
                    entries.add(ModBlocks.WEATHERED_COPPER_CHAIN);
                    entries.add(ModBlocks.OXIDISED_COPPER_CHAIN);
                    entries.add(ModBlocks.COPPER_BARS);
                    entries.add(ModBlocks.EXPOSED_COPPER_BARS);
                    entries.add(ModBlocks.WEATHERED_COPPER_BARS);
                    entries.add(ModBlocks.OXIDISED_COPPER_BARS);
                    entries.add(ModBlocks.WAXED_COPPER_CHAIN);
                    entries.add(ModBlocks.WAXED_EXPOSED_COPPER_CHAIN);
                    entries.add(ModBlocks.WAXED_WEATHERED_COPPER_CHAIN);
                    entries.add(ModBlocks.WAXED_OXIDISED_COPPER_CHAIN);
                    entries.add(ModBlocks.WAXED_COPPER_BARS);
                    entries.add(ModBlocks.WAXED_EXPOSED_COPPER_BARS);
                    entries.add(ModBlocks.WAXED_WEATHERED_COPPER_BARS);
                    entries.add(ModBlocks.WAXED_OXIDISED_COPPER_BARS);
                    entries.add(ModBlocks.SULFUR_BLOCK);
                    entries.add(ModBlocks.GOLD_CHAIN);
                    entries.add(ModBlocks.GOLD_BARS);
                    entries.add(ModBlocks.LIMESTONE);
                    entries.add(ModBlocks.LIMESTONE_SLAB);
                    entries.add(ModBlocks.LIMESTONE_STAIRS);
                    entries.add(ModBlocks.LIMESTONE_WALL);
                    entries.add(ModBlocks.POLISHED_LIMESTONE);
                    entries.add(ModBlocks.POLISHED_LIMESTONE_SLAB);
                    entries.add(ModBlocks.POLISHED_LIMESTONE_STAIRS);
                    entries.add(ModBlocks.POLISHED_LIMESTONE_WALL);
                    entries.add(ModBlocks.LIMESTONE_BRICKS);
                    entries.add(ModBlocks.LIMESTONE_BRICK_SLAB);
                    entries.add(ModBlocks.LIMESTONE_BRICK_STAIRS);
                    entries.add(ModBlocks.LIMESTONE_BRICK_WALL);
                    entries.add(ModBlocks.ICE_ROCK);
                    entries.add(ModBlocks.ICE_ROCK_SLAB);
                    entries.add(ModBlocks.ICE_ROCK_STAIRS);
                    entries.add(ModBlocks.ICE_ROCK_WALL);
                    entries.add(ModBlocks.POLISHED_ICE_ROCK);
                    entries.add(ModBlocks.POLISHED_ICE_ROCK_SLAB);
                    entries.add(ModBlocks.POLISHED_ICE_ROCK_STAIRS);
                    entries.add(ModBlocks.POLISHED_ICE_ROCK_WALL);
                    entries.add(ModBlocks.ICE_ROCK_BRICKS);
                    entries.add(ModBlocks.ICE_ROCK_BRICK_SLAB);
                    entries.add(ModBlocks.ICE_ROCK_BRICK_STAIRS);
                    entries.add(ModBlocks.ICE_ROCK_BRICK_WALL);
                    entries.add(ModBlocks.AURORITE_CRYSTAL_BLOCK);
                    entries.add(ModBlocks.AURORITE_BLOCK);
                    entries.add(ModBlocks.JADE_BLOCK);
                    entries.add(ModBlocks.JADE_BRICKS);
                    entries.add(ModBlocks.JADE_BRICK_SLAB);
                    entries.add(ModBlocks.JADE_BRICK_STAIRS);
                    entries.add(ModBlocks.JADE_BRICK_WALL);
                    entries.add(ModBlocks.TIN_BLOCK);
                    entries.add(ModBlocks.RAW_TIN_BLOCK);
                    entries.add(ModBlocks.CUT_TIN);
                    entries.add(ModBlocks.CUT_TIN_SLAB);
                    entries.add(ModBlocks.CUT_TIN_STAIRS);
                    entries.add(ModBlocks.CHISELED_TIN);
                    entries.add(ModBlocks.TIN_GRATE);
                    entries.add(ModBlocks.TIN_CHAINS);
                    entries.add(ModBlocks.TIN_BARS);
                    entries.add(ModBlocks.TIN_DOOR);
                    entries.add(ModBlocks.TIN_TRAPDOOR);
                    entries.add(ModBlocks.STEEL_BLOCK);
                    entries.add(ModBlocks.STEEL_CHAINS);
                    entries.add(ModBlocks.STEEL_BARS);
                    entries.add(ModBlocks.SCULK_SLATE);
                    entries.add(ModBlocks.SCULK_SLATE_BRICKS);
                    entries.add(ModBlocks.SCULK_SLATE_BRICK_SLAB);
                    entries.add(ModBlocks.SCULK_SLATE_BRICK_STAIRS);
                    entries.add(ModBlocks.SCULK_SLATE_BRICK_WALL);
                }
        );
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.NATURAL).register(
                entries -> {
                    entries.add(ModBlocks.SULFUR_ORE);
                    entries.add(ModBlocks.JADE_ORE);
                    entries.add(ModBlocks.DEEPSLATE_JADE_ORE);
                    entries.add(ModBlocks.TIN_ORE);
                    entries.add(ModBlocks.DEEPSLATE_TIN_ORE);
                    entries.add(ModBlocks.AURORITE_CRYSTAL_BLOCK);
                    entries.add(ModBlocks.BUDDING_AURORITE);
                    entries.add(ModBlocks.AURORITE_CLUSTER);
                    entries.add(ModBlocks.SMALL_AURORITE_BUD);
                    entries.add(ModBlocks.MEDIUM_AURORITE_BUD);
                    entries.add(ModBlocks.LARGE_AURORITE_BUD);
                }
        );
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.FUNCTIONAL).register(
                entries -> {
                    entries.add(ModItems.COPPER_TORCH);
                    entries.add(ModBlocks.COPPER_LANTERN);
                    entries.add(ModBlocks.EXPOSED_COPPER_LANTERN);
                    entries.add(ModBlocks.WEATHERED_COPPER_LANTERN);
                    entries.add(ModBlocks.OXIDISED_COPPER_LANTERN);
                    entries.add(ModBlocks.WAXED_COPPER_LANTERN);
                    entries.add(ModBlocks.WAXED_EXPOSED_COPPER_LANTERN);
                    entries.add(ModBlocks.WAXED_WEATHERED_COPPER_LANTERN);
                    entries.add(ModBlocks.WAXED_OXIDISED_COPPER_LANTERN);
                    entries.add(ModItems.SULFUR_TORCH);
                    entries.add(ModBlocks.GOLD_LANTERN);
                    entries.add(ModItems.TIN_TORCH);
                    entries.add(ModBlocks.TIN_LANTERN);
                    entries.add(ModBlocks.STEEL_LANTERN);
                }
        );
    }
}
